
CREATE table YELLOW (
ID INT PRIMARY KEY,
CAT_NAME varchar(50),
WORDY_1 varchar(50),
WORDY_2 varchar(50),
WORDY_3 varchar(50),
WORDY_4 varchar(50)
);

INSERT into YELLOW values (1, 'FLABBERGAST' ,'FLOOR', 'ROCK', 'SHOCK', 'SURPRISE');
INSERT into YELLOW values (2, 'ORDERLY', 'CLEAN', 'NEAT', 'TIDY', 'TRIM');
INSERT into YELLOW values (3, 'BREATHES HEAVILY', 'GASPS', 'HUFFS', 'PANTS', 'PUFFS');
INSERT into YELLOW values (4, 'JUMPING ANIMALS', 'CRICKET', 'FROG', 'HARE', 'KANGAROO');
INSERT into YELLOW values (5, 'SEGMENT OF A PROCESS', 'CYCLE', 'PHASE', 'ROUND', 'STAGE');
INSERT into YELLOW values (6, 'FOOLISHNESS', 'ABSURDITY', 'FOLLY', 'MADNESS', 'NONSENSE');
INSERT into YELLOW values (7, 'CRITICIZE', 'BLAST', 'KNOCK', 'SLAM', 'TRASH');
INSERT into YELLOW values (8, 'INTELLIGENCE OPERATIVE', 'AGENT', 'ASSET', 'MOLE', 'SLEEPER');
INSERT into YELLOW values (9, 'GARLIC BREAD INGREDIENTS', 'BREAD', 'BUTTER', 'GARLIC', 'PARSLEY');
INSERT into YELLOW values (10, 'CHEESES FAMILIARLY', 'AMERICAN', 'BLUE', 'JACK', 'SWISS');
INSERT into YELLOW values (11, 'BASIC TASTES', 'BITTER', 'SALTY', 'SOUR', 'SWEET');
INSERT into YELLOW values (12, 'MANUFACTURING LOCATIONS', 'FACTORY', 'MILL', 'PLANT', 'SHOP');
INSERT into YELLOW values (13, 'DOG SOUNDS', 'BARK', 'GROWL', 'HOWL', 'WHINE'); 
INSERT into YELLOW values (14, 'PESTERS', 'BADGERS', 'BUGS', 'HOUNDS', 'NAGS');
INSERT into YELLOW values (15, 'PARTY POOPER', 'BORE', 'DRAG', 'DRIP', 'DUD');
INSERT into YELLOW values (16, 'USED IN BUILDING A FIRE', 'KINDLING', 'LOG', 'MATCH', 'TINDER');
INSERT into YELLOW values (17, 'EAT A LITTLE', 'GRAZE', 'NIBBLE', 'PECK', 'SNACK');
INSERT into YELLOW values (18, 'COMFY SHOES', 'CROC', 'LOAFER', 'MOCCASIN', 'SLIPPER');
INSERT into YELLOW values (19, 'DRINKS WITH CAFFEINE', 'COCOA', 'COFFEE', 'MATE', 'TEA');
INSERT into YELLOW values (20, 'BAD THINGS FOR A VIDEO CALL TO DO', 'DROP', 'ECHO', 'FREEZE', 'LAG');
INSERT into YELLOW values (21, 'MUSIC PLAYER BUTTONS', 'REWIND', 'SHUFFLE', 'SKIP', 'STOP');
INSERT into YELLOW values (22, 'ARCHERY EQUIPMENT', 'ARROW', 'BOW', 'QUIVER', 'TARGET');
INSERT into YELLOW values (23, 'SEA CREATURES', 'CRAB', 'RAY', 'SPONGE', 'SQUID');
INSERT into YELLOW values (24, 'THINGS THAT ARE ORANGE', 'BASKETBALL', 'CARROT', 'GOLDFISH', 'PUMPKIN');
INSERT into YELLOW values (25, 'TYPES OF DUCKS', 'MALLARD', 'MOTTLED', 'RUBBER', 'WOOD');



CREATE TABLE GREEN(
ID INT PRIMARY KEY,
CAT_NAME VARCHAR(100),
WORDG_1 VARCHAR(100),
WORDG_2 VARCHAR(100),
WORDG_3 VARCHAR(100),
WORDG_4 VARCHAR(100)
);

insert into GREEN values(1, "BIT OF JOURNALISM", "ARTICLE", "FEATURE", "REPORT", "STORY");
insert into GREEN values(2, "AUGMENTATIVE PREFIXES", "HYPER", "SUPER", "UBER", "ULTRA");
insert into GREEN values(3, "PRESERVES, AS MEAT", "CANS", "CURES", "SALTS", "SMOKES");
insert into GREEN values(4, "APPLY PRESSURE TO", "CRUSH", "MASH", "PRESS", "SQUASH");
insert into GREEN values(5, "CONSTELLATIONS", "CYGNUS", "GEMINI", "ORION", "PEGASUS");
insert into GREEN values(6, "MOVE FORWARD", "ADVANCE", "MARCH", "PROGRESS", "PUSH");
insert into GREEN values(7, "“MY MISTAKE!”", "APOLOGIES", "OOPS", "PARDON", "SORRY");
insert into GREEN values(8, "UNITS IN POETRY", "FOOT", "LINE", "METER", "VERSE");
insert into GREEN values(9, "WAGER", "BET", "GAMBLE", "RISK", "STAKE");
insert into GREEN values(10, "TRACK AND FIELD EQUIPMENT", "HAMMER", "HURDLE", "JAVELIN", "POLE");
insert into GREEN values(11, 'STAND UP TO AS A CHALLENGE', 'BRAVE', 'CONFRONT', 'FACE', 'MEET');
insert into GREEN values(12, 'WIN + LETTER', 'WIND', 'WINE', 'WING', 'WINK');
insert into GREEN values(13, 'SHADES OF GREEN', 'OLIVE', 'FOREST', 'LIME', 'MINT');
insert into GREEN values(14, 'MUSICAL SECTIONS', 'BRASS', 'RHYTHM', 'STRING', 'WIND');
insert into GREEN values(15, 'MEDIA ATTENTION', 'COVERAGE', 'EXPOSURE', 'PRESS', 'PUBLICITY');
insert into GREEN values(16, 'MESS UP', 'BLOW', 'BUMBLE', 'FLUFF', 'SPOIL');
insert into GREEN values(17, 'KINDS OF NUMBERS', 'ODD', 'PERFECT', 'PRIME', 'WHOLE');
insert into GREEN values(18, 'THINGS MADE WITH FEATHERS', 'BOA', 'HEADDRESS', 'PILLOW', 'SHUTTLECOCK');
insert into GREEN values(19, 'WHERE YOU MIGHT FIND SAND', 'BEACH', 'DESERT', 'HOURGLASS', 'PLAYGROUND');
insert into GREEN values(20, 'SPHERICAL FOODS', 'JAWBREAKER', 'MEATBALL', 'MOZZARELLA', 'ORANGE');
insert into GREEN values(21, 'CARD GAMES', 'BRIDGE', 'GIN', 'SPIT', 'WAR');
insert into GREEN values(22, 'BASIC TWO-DIMENSIONAL SHAPES', 'CIRCLE', 'DIAMOND', 'SQUARE', 'TRIANGLE');
insert into GREEN values(23, 'UNEXCITING', 'BORING', 'DULL', 'MUNDANE', 'VANILLA');
insert into GREEN values(24, 'MOVE BACK AND FORTH', 'ROCK', 'SWAY', 'SWING', 'WAVE');
insert into GREEN values(25, 'TEACHERS WE HAVE', 'MOOD', 'LEIH', 'CROCKETT', 'ZACK');

CREATE TABLE BLUE (
ID INT PRIMARY KEY,
CAT_NAME varchar(50),
WORDB_1 varchar(50),
WORDB_2 varchar(50),
WORDB_3 varchar(50),
WORDB_4 varchar(50)
);

INSERT INTO BLUE VALUES (1, "ON THE SAME PLANE", "EVEN", "FLAT", "FLUSH", "LEVEL");
INSERT INTO BLUE VALUES (2, "BECOME LARGER", "BALLOON", "MUSHROOM", "SNOWBALL", "SWELL");
INSERT INTO BLUE VALUES (3, "PREDICAMENTS", "BINDS", "JAMS", "PICKLES", "SPOTS");
INSERT INTO BLUE VALUES (4, "OLYMPIC SPORTS", "BREAKING", "HOCKEY", "SKELETON", "TRAMPOLINE");
INSERT INTO BLUE VALUES (5, "SPIRALS IN NATURE", "CYCLONE", "GALAXY", "SNAIL", "SUNFLOWER");
INSERT INTO BLUE VALUES (6, "THINGS THAT MIGHT STINK", "CHEESE", "FEET", "GARBAGE", "SKUNK");
INSERT INTO BLUE VALUES (7, "ALIBI", "DEFENSE", "EXCUSE", "OUT", "REASON");
INSERT INTO BLUE VALUES (8, "EXPRESS INDIRECTLY", "COUCH", "IMPLY", "INTIMATE", "SUGGEST");
INSERT INTO BLUE VALUES (9, "DISNEYLAND LANDS", "ADVENTURE", "FANTASY", "FRONTIER", "TOMORROW");
INSERT INTO BLUE VALUES (10, "KINDS OF HEELS", "CUBAN", "KITTEN", "STILETTO", "WEDGE");
INSERT INTO BLUE VALUES (11, 'FENCING EQUIPMENT', 'FOIL', 'GLOVE', 'JACKET', 'MASK');
INSERT INTO BLUE VALUES (12, 'PARTS OF FRUIT YOU MIGHT NOT EAT', 'CORE', 'RIND', 'SEED', 'STEM');
INSERT INTO BLUE VALUES (13, 'THEY HAVE KEYS', 'COMPUTER', 'PIANO', 'SUPER', 'TESTS');
INSERT INTO BLUE VALUES (14, 'BIT OF LIQUID', 'BEAD', 'DROP', 'GLOB', 'TEAR');
INSERT INTO BLUE VALUES (15, 'INGREDIENTS IN MINESTRONE', 'BEANS', 'PASTA', 'STOCK', 'VEGETABLES');
INSERT INTO BLUE VALUES (16, 'WORKSHOP TOOLS', 'DRILL', 'GRINDER', 'ROUTER', 'SAW');
INSERT INTO BLUE VALUES (17, 'CAPTAINS', 'AMERICA', 'HOOK', 'MORGAN', 'NEMO');
INSERT INTO BLUE VALUES (18, 'PROGRAMMING LANGUAGES', 'BASIC', 'JAVA', 'PYTHON', 'RUBY');
INSERT INTO BLUE VALUES (19, 'OVEN BUTTONS', 'BAKE', 'BROIL', 'LIGHT', 'TIMER');
INSERT INTO BLUE VALUES (20, 'YOGA POSES', 'CAT', 'COW', 'MOUNTAIN', 'TRIANGLE');
INSERT INTO BLUE VALUES (21, 'THINGS YOU CAN DRAW', 'BATH', 'CARD', 'CURTAIN', 'PICTURE');
INSERT INTO BLUE VALUES (22, 'RHYMES', 'CHOIR', 'FIRE', 'LIAR', 'FRYER');
INSERT INTO BLUE VALUES (23, 'CLASSIC DOG NAMES', 'FLUFFY', 'REX', 'ROVER', 'SPOT');
INSERT INTO BLUE VALUES (24, 'COMEDIAN’S PERFORMANCE', 'ACT', 'BIT', 'ROUTINE', 'SET');
INSERT INTO BLUE VALUES (25, 'WHAT WE MADE OUR FANPAGES ON', 'LITTLE WOMEN', 'STAR WARS', 'PUNXSUTAWNEY PHIL', 'TAYLOR SWIFT');



CREATE TABLE PURPLE
(
ID INT PRIMARY KEY,
CAT_NAME VARCHAR(50),
WORDP_1 VARCHAR(50),
WORDP_2 VARCHAR(50),
WORDP_3 VARCHAR(50),
WORDP_4 VARCHAR(50)
);

INSERT INTO PURPLE VALUES (1, 'THEATER SECTIONS', 'BALCONY', 'BOX', 'ORCHESTRA', 'STAGE');
INSERT INTO PURPLE VALUES (2, 'ITEMS IN CLASSIC KIDS GAMES', 'DOMINO', 'JACK', 'MARBLE', 'STICK');
INSERT INTO PURPLE VALUES (3, 'THINGS IN MY FAVORITE THINGS', 'KETTLES', 'MITTENS', 'RAINDROPS', 'WHISKERS');
INSERT INTO PURPLE VALUES (4, 'THINGS YOU CAN SET', 'MOOD', 'RECORD', 'TABLE', 'VOLLEYBALL');
INSERT INTO PURPLE VALUES (5, 'ASSOCIATED WITH ONE', 'CYCLOPS', 'MONOLOGUE', 'SOLITAIRE', 'UNICYCLE');
INSERT INTO PURPLE VALUES (6, 'WORDS AFTER DEEP', 'CUT', 'FAKE', 'FREEZE', 'SIX');
INSERT INTO PURPLE VALUES (7, 'PLAY ___', 'DATE', 'DEAD', 'DIRTY', 'DOH');
INSERT INTO PURPLE VALUES (8, 'WHAT K MIGHT MEAN', 'KELVIN', 'OKAY', 'POTASSIUM', 'THOUSAND');
INSERT INTO PURPLE VALUES (9, '___ BAT', 'BASEBALL', 'CRICKET', 'FRUIT', 'VAMPIRE');
INSERT INTO PURPLE VALUES (10, 'DOUBLE ___', 'DATE', 'DUTCH', 'JEOPARDY', 'SPACE');
INSERT INTO PURPLE VALUES (11, 'THINGS WITH SPINES', 'BOOK', 'CACTUS', 'HEDGEHOG', 'SKELETON');
INSERT INTO PURPLE VALUES (12, 'WEIGHTS IN BOXING', 'FEATHER', 'HEAVY', 'LIGHT', 'MIDDLE');
INSERT INTO PURPLE VALUES (13, 'COLORS WITH THEIR FIRST LETTERS CHANGED', 'CLUE', 'FROWN', 'MELLOW', 'PREEN');
INSERT INTO PURPLE VALUES (14, 'SCHOOL OF ___', 'FISH', 'HARD KNOCKS', 'ROCK', 'THOUGHT');
INSERT INTO PURPLE VALUES (15, 'GO ___', 'BANANAS', 'FIGURE', 'FISH', 'STEADY');
INSERT INTO PURPLE VALUES (16, 'PARTS OF A DOOR', 'FRAME', 'HANDLE', 'HINGE', 'LOCK');
INSERT INTO PURPLE VALUES (17, 'BEAR ___', 'CLAW', 'FRUIT', 'HUG', 'WITNESS');
INSERT INTO PURPLE VALUES (18, 'THINGS THAT CAN STRIKE', 'COBRA', 'INSPIRATION', 'LIGHTNING', 'UNION');
INSERT INTO PURPLE VALUES (19, 'MOVIES MINUS NUMBERS', 'APOLLO', 'CANDLES', 'FANTASTIC', 'SAMURAI');
INSERT INTO PURPLE VALUES (20, '___FLY', 'BUTTER', 'DRAGON', 'FIRE', 'HORSE');
INSERT INTO PURPLE VALUES (21, 'NUMBER ANAGRAMS', 'EON', 'ETHER', 'NET', 'TOW');
INSERT INTO PURPLE VALUES (22, 'CLASSIC TATTOOS', 'ANCHOR', 'DRAGON', 'HEART', 'ROSE');
INSERT INTO PURPLE VALUES (23, 'FANCY ___', 'FEAST', 'FREE', 'PANTS', 'THAT');
INSERT INTO PURPLE VALUES (24, 'COLORS MINUS THEIR FIRST LETTERS', 'INK', 'LACK', 'OLD', 'RANGE');
INSERT INTO PURPLE VALUES (25, 'LITTLE WOMEN SISTERS MINUS BETH PLUS SAM', 'SAM', 'AMY', 'JO', 'MEG');
